# Generated by Django 2.1.3 on 2018-11-23 11:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0003_person_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('document_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RenameField(
            model_name='event',
            old_name='document_date',
            new_name='event_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='document_number',
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='father',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='father_child', to='life.Person'),
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('ML', 'мужской'), ('FM', 'женский')], default='ML', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='mobile',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='mother',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mother_child', to='life.Person'),
        ),
        migrations.AddField(
            model_name='person',
            name='passport',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='snils',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='life.Document'),
        ),
    ]
