# Generated by Django 2.1.3 on 2018-12-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0006_auto_20181123_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personeducation',
            name='finish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
