# Generated by Django 2.1.3 on 2018-12-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0007_auto_20181223_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personeducation',
            old_name='person',
            new_name='pupil',
        ),
        migrations.AlterField(
            model_name='person',
            name='educations',
            field=models.ManyToManyField(through='life.PersonEducation', to='life.Education'),
        ),
    ]
