# Generated by Django 2.1.3 on 2018-12-23 14:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0008_auto_20181223_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('finish_date', models.DateTimeField(blank=True, null=True)),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='life.Education')),
            ],
        ),
        migrations.RemoveField(
            model_name='personeducation',
            name='education',
        ),
        migrations.RemoveField(
            model_name='personeducation',
            name='pupil',
        ),
        migrations.AlterField(
            model_name='person',
            name='educations',
            field=models.ManyToManyField(through='life.Pupil', to='life.Education'),
        ),
        migrations.DeleteModel(
            name='PersonEducation',
        ),
        migrations.AddField(
            model_name='pupil',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='life.Person'),
        ),
    ]
